title: Victor Ileaboya Data Analytics Portfolio
logo: victor.jpg
description: A Data analyst with two years experience working accross different sectors, Highly skilled in Excel, Power BI and SQL.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
